reload('user.keymaps')
reload('user.options')
reload('user.plugins')

reload('user.lsp')
reload('user.null-ls')
reload('user.treesitter')

reload('user.nvimtree')
reload('user.telescope')
reload('user.bufferline')
reload('user.undotree')
reload('user.copilot')
reload('user.alpha')
reload('user.trouble')
reload('user.markdown-preview')
reload('user.spectre')
reload('user.leap')
reload('user.which-key')
reload('user.todo-comments')
reload('user.toggleterm')
reload('user.dap')
reload('user.diffview')
